# Generated by Django 6.0.3 on 2026-03-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='sahifa_soni',
            field=models.PositiveIntegerField(),
        ),
    ]
